# Use the official OpenJDK base image
FROM openjdk:17-jdk-slim

# Set the working directory
WORKDIR /app

# Copy the JAR file into the container at /app
COPY  build/libs/vehicle-0.0.1-SNAPSHOT.jar /app/vehicleservice.jar

# Specify the command to run on container start
CMD ["java", "-jar", "vehicleservice.jar"]

EXPOSE 8003